version: "3.9"

services:
  backend:
    build: ./backend-docker-info-api
    ports:
      - "3001:3001"
    networks:
      - appnet

  project1:
    build: ./project1-csc424-home
    ports:
      - "5173:5173"
    networks:
      - appnet

  project2:
    build: ./project2-docker-info
    ports:
      - "5174:5174"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - project1
      - project2
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

